### ISSUE TITLE
Create issues via slack

### ISSUE THREAD

**Issue by ovv** [pyslackers/sirbot-pythondev#2]
ndevox: We should add a way to create issues from slack and see what are the current issues
We could add a check for user to avoid abuse

**Comment by ovv** [comment]
Shawn McElroy @autoferrit commented 7 months ago

we could also provide a special channel for core contributors to do it in as a second level. A private channel.
we could also limit it to only check for the message in one of the community channels. or whatever channel is appropriate. such as #bot-development for the bot repo. Just thoughts.

**Comment by mattrasband** [comment]
I'm not sure this is a feature that makes a lot of sense for us. Primarily because a large part of what we are doing as a community is educating people on how to work in the open source (and professional) worlds, and a large part of that is filing/searching issues.

What does this buy us other than pointing people over to GitHub so they can get the "internet points"?

**Comment by ovv** [comment]
good points @mrasband.

I guess we can close that then
